oyepriyansh/DevProfiles

- index.html
adding my profile to your repo, don't forget to mark this hacktoberfest accepted :)
> Profile Update

- index.html
Hi @oyepriyansh,
please add tag for hacktoberfest accepted
> Added Profile Sunil

- index.html
please check and accept as part of hacktoberfest
thanks
> added my details in HTML file

- index.html
> added myself :3c

- index.html
Please consider accept my PRs.
> Update: Add Michael Ortiz

- index.html
Added my devprofiles, requested you to please merge the pr
Thankyou.
> first good issue

- index.html
- style.css
> Modified the changes in index.html and skills and social div container to flexbos

- index.html
> Added my profile to the list

- index.html
Hey there, I added a profile.
had fun working in this repo.
> Added profile -Balajithegr8

- index.html
> new profile

- index.html
I have added my profile to the list in accordance with Hacktoberfest !
> add : new profile

- index.html
Hi,
I have created my dev profile.
Pls review and merge my PR.
> Added my dev profile

- index.html
Hey i have added my profile in this branch.
Please merge it in hackertober fest label.
> Add: my profile index.html

- index.html
I added my profile please review it.
> Adding New Profile (Ahasas Jain)

- index.html
> Create Profile 

- index.html
Updated index.html with my details .
> Updated index.html with my details

- index.html
Added my profile as per readme.
> Add my profile

- index.html
I have updated my profile
Thanks
> added new profile

- README.md
- index.html
- script.js
- style.css
I have made the changes. Kindly check if they are all right or do I have to change something. Thanks :)
> Improved UI and introduced dark and light mode switching

- index.html
Added My Profile and able to merge.
> [Added] Adding profile

- index.html
> adding my profile detail ✨

- index.html
i have added my profile in main branch plz accept this PR
`<div class="profile">
<div class="pfp"><img src="https://github.com/vishalverma9572/responsiveness/blob/b74ab59849d8d9e0e328bf263d104432524202de/WhatsApp%20Image%202023-10-05%20at%2017.13.48_c3f1c808.jpg?raw=true" alt="User Image"></div>
<h3 class="name">Vishal Kumar</h3>
<div class="skills">
<span class="skill">Frontend Developer</span>
<span class="skill">OpenSource</span>
<span class="skill">DBMS</span>
<span class="skill">C++</span>
<span class="skill">Python</span>
</div>
<div class="social">
<a href="https://github.com/vishalverma9572/" target="_blank"><i class="fa-brands fa-github"></i></a>
<a href="https://www.linkedin.com/in/vishal-kumar-375a25250?" target="_blank"><i class="fa-brands fa-x-twitter"></i></a>
<a …
> profile of vishal merged  in index.html

- index.html
I added my profile to the index.html file.
Please merge.
Thanks.
> Added my profile: Sammie

- index.html
> Added new profile 

- CONTRIBUTING.md
- README.md
Hello , Please have a look on the contributing.md file and let me know any issue .
Thankyou !
> Added Contributing.md and updated readme file

- index.html
This PR fixes #112 
Please Merge this PR
> Added My profile

- index.html
data: profile addition by Abayomi Ogunnusi: drsimplegraffiti
> data: profile addition by Abayomi Ogunnusi: drsimplegraffiti

- index.html
> data: profile addition by Septian Maulana

- index.html
Chore : Add Profile inside index.html
> Chore : Profile Additon  

- index.html
Hello there @oyepriyansh . I have added my profile with the issue #102 . Please review it. Thank you😊.
> profile addition by Arnab Barua

- css/style.css
- index.html
- js/script.js
below is the output video :
https://github.com/oyepriyansh/DevProfiles/assets/98396468/0c75c253-f788-466f-a084-0c4e60454315
> Solve #49 : Enhanced User experience 

- index.html
> This PR adds my profile

- index.html
> Profile added

- css/style.css
- index.html
Changes:-
1. Added some transitions in all the profile div.
2. Improving the navbar slightly.
3. Improving add profile section.
4. Improving the overall attractiveness of the website.
> First commit (Add profile and added some animations) etc.

- index.html
Added my Dev Profile to the page.
> data: profile addition by Ashmit Mehta (Ash-codes18)

- index.html
Profile addition by zirea3l(Piyush)
Update in index.html
> Profile addition by zirea3l(Piyush)

- .vscode/settings.json
- index.html
- js/script.js
fixed the on hover text issue 
fixes #170 
on hover 
without hover
> fixed-light-mode-text-issue

- index.html
> Added Profile

- index.html
Added my profile in your website as i raising #181 
Please my PR with you repository
> Profile added by Dhiman-Nayak

- index.html
Added new member BilalMirza74
fixed #183
> Added new member and fixed #183

- index.html
This PR added my profile in the DevProfiles.
Fixes #187
> Added my profile in devprofiles

- index.html
> data: profile addition by Rohit Kumar Dey

- index.html
Adding my profile with my skills, links and pfp
> adding Rémi's profile

- css/style.css
Fixed the issue #203 
This is how it currently works.
https://github.com/oyepriyansh/DevProfiles/assets/102857774/f8f7d009-f296-4b1e-a564-249cc1065a63
> fixed the overflow of dark mode button

- index.html
> data: profile addition by Mehmet 

- css/style.css
- index.html
Added a back to top FAB for better UI experience
> added back-to-top FAB

- css/style.css
- index.html
fixed background and icon color for back to top FAB
> Fixed bg color for Back to top FAB

- index.html
> My Dev Profile

- index.html
> Add DevProfile 

- data.json
data: profile addition by Emmanuel P. Barrameda
> data: profile addition by Emmanuel P. Barrameda

- data.json
> data: profile addition by Zaid

- data.json
> data: added profile by Hailey Martin

- README.md
- scripts/app.js
Updated App.js with a search function in the url bar and fallback image to GitHub if no image is provided and if that is not found it will use the defaultimage from App.js
I also updated README.md with a star history of how many stars the repo has gotten since it was created
> Updated App.js

- data.json
This PR will add `gaurovgiri` (myself) to the data.json along with my skills and link to profiles.
> data: profile addition by gaurovgiri

- data.json
This PR will add `aayush105` (myself) to the data.json along with my skills and link to profiles.
> data: profile addition by aayush105

- data.json
> data: profile addition by Khail Sakdalan 

- data.json
> data: profile addition by Vensin

- data.json
This pull request adds the profile details of Pratima Sapkota, including her GitHub, LinkedIn, and skills.
> Profile addition by Pratima Sapkota

- data.json
> add new profile

- scripts/app.js
> UX: focus on searchinput onload
